"""This is the test module for the markdown module"""

import unittest
from unittest.mock import mock_open, patch

import contributor_stats
from markdown import write_to_markdown


class TestMarkdown(unittest.TestCase):
    """
    Test case for the markdown module.
    """

    @patch("markdown.os.environ.get", return_value=None)  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown(self, mock_file, mock_env_get):
        """
        Test the write_to_markdown function.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            False,
            "url2",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initiatization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Username | All Time Contribution Count | New Contributor | Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- |\n"
            "| @user1 | 100 | False | commit url |\n"
            "| @user2 | 200 | True | commit url2 |\n"
            "\n _this file was generated by the [Contributors GitHub Action](https://github.com/github/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch("markdown.os.environ.get", return_value=None)  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_with_sponsors(self, mock_file, mock_env_get):
        """
        Test the write_to_markdown function with sponsors info turned on.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            False,
            "url2",
            200,
            "commit url2",
            "",
        )
        # Set person2 as a new contributor since this cannot be set on initiatization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "true",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Username | All Time Contribution Count | New Contributor | Sponsor URL | Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- |\n"
            "| @user1 | 100 | False | [Sponsor Link](sponsor_url_1) | commit url |\n"
            "| @user2 | 200 | True | not sponsorable | commit url2 |\n"
            "\n _this file was generated by the [Contributors GitHub Action](https://github.com/github/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch("markdown.os.environ.get", return_value=None)  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_without_link_to_profile(self, mock_file, mock_env_get):
        """
        Test the write_to_markdown function with link to profile turned off.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            False,
            "url2",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initiatization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            False,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Username | All Time Contribution Count | New Contributor | Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- |\n"
            "| user1 | 100 | False | commit url |\n"
            "| user2 | 200 | True | commit url2 |\n"
            "\n _this file was generated by the [Contributors GitHub Action](https://github.com/github/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch("markdown.os.environ.get", return_value="/tmp/step_summary")
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_github_summary(self, mock_file, mock_env_get):
        """
        Test that markdown content is written to GitHub Step Summary when environment variable is set.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            False,
            "url2",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initiatization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            True,
            ghe,
        )

        # Verify that open was called twice - once for the markdown file and once for the step summary
        self.assertEqual(mock_file.call_count, 2)
        
        # Verify the first call is for the markdown file
        first_call = mock_file.call_args_list[0]
        self.assertEqual(first_call[0], ("filename", "w"))
        self.assertEqual(first_call[1]["encoding"], "utf-8")
        
        # Verify the second call is for the step summary file
        second_call = mock_file.call_args_list[1]
        self.assertEqual(second_call[0], ("/tmp/step_summary", "a"))
        self.assertEqual(second_call[1]["encoding"], "utf-8")


if __name__ == "__main__":
    unittest.main()
