"""This is the test module for the markdown module"""

import unittest
from unittest.mock import mock_open, patch

import contributor_stats
from markdown import write_to_markdown


class TestMarkdown(unittest.TestCase):
    """
    Test case for the markdown module.
    """

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "@company1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            "@company2",
            False,
            "url2",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initialization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Username | Company | All Time Contribution Count | New Contributor | "
            "Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- |\n"
            "| @user1 | @company1 | 100 | False | commit url |\n"
            "| @user2 | @company2 | 200 | True | commit url2 |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_with_sponsors(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function with sponsors info turned on.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "@company1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            "@company2",
            False,
            "url2",
            200,
            "commit url2",
            "",
        )
        # Set person2 as a new contributor since this cannot be set on initialization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "true",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Username | Company | All Time Contribution Count | New Contributor | "
            "Sponsor URL | Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- | --- |\n"
            "| @user1 | @company1 | 100 | False | [Sponsor Link](sponsor_url_1) | commit url |\n"
            "| @user2 | @company2 | 200 | True | not sponsorable | commit url2 |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_with_avatars(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function with avatar images turned on.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "",
            False,
            "https://avatars.example.com/user1.png",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            "",
            False,
            "https://avatars.example.com/user2.png",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initialization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            True,
            ghe,
            show_avatar=True,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Avatar | Username | Company | All Time Contribution Count | New Contributor | "
            "Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- | --- |\n"
            '| <img src="https://avatars.example.com/user1.png" width="32" height="32" /> | '
            "@user1 | - | 100 | False | commit url |\n"
            '| <img src="https://avatars.example.com/user2.png" width="32" height="32" /> | '
            "@user2 | - | 200 | True | commit url2 |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_empty_company_falls_back(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function with an empty company value.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        collaborators = [
            person1,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 1 | 100 | 0.0% |\n\n"
            "| Username | Company | All Time Contribution Count | New Contributor | "
            "Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- |\n"
            "| @user1 | - | 100 | False | commit url |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_without_link_to_profile(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function with link to profile turned off.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "@company1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            "@company2",
            False,
            "url2",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initialization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            False,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Username | Company | All Time Contribution Count | New Contributor | "
            "Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- |\n"
            "| user1 | @company1 | 100 | False | commit url |\n"
            "| user2 | @company2 | 200 | True | commit url2 |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch("markdown.os.environ.get", return_value="/tmp/step_summary")
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_github_summary(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test that markdown content is written to GitHub Step Summary
        when environment variable is set.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "@company1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            "@company2",
            False,
            "url2",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initialization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            True,
            ghe,
        )

        # Verify that open was called twice - once for the markdown file
        # and once for the step summary
        self.assertEqual(mock_file.call_count, 2)

        # Verify the first call is for the markdown file
        first_call = mock_file.call_args_list[0]
        self.assertEqual(first_call[0], ("filename", "w"))
        self.assertEqual(first_call[1]["encoding"], "utf-8")

        # Verify the second call is for the step summary file
        second_call = mock_file.call_args_list[1]
        self.assertEqual(second_call[0], ("/tmp/step_summary", "a"))
        self.assertEqual(second_call[1]["encoding"], "utf-8")

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_with_organization(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function with organization specified.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "@company1",
            False,
            "url",
            100,
            "https://github.com/org1/repo1/commits?author=user1",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            "@company2",
            False,
            "url2",
            200,
            "https://github.com/org2/repo2/commits?author=user2, "
            "https://github.com/org3/repo3/commits?author=user2",
            "sponsor_url_2",
        )
        # Set person2 as a new contributor since this cannot be set on initialization of the object
        person2.new_contributor = True
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            "test-org",
            None,
            "false",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Organization: test-org\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 2 | 300 | 50.0% |\n\n"
            "| Username | Company | All Time Contribution Count | New Contributor | "
            "Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- |\n"
            "| @user1 | @company1 | 100 | False | "
            "[org1/repo1](https://github.com/org1/repo1/commits?author=user1),  |\n"
            "| @user2 | @company2 | 200 | True | "
            "[org2/repo2](https://github.com/org2/repo2/commits?author=user2), "
            "[org3/repo3](https://github.com/org3/repo3/commits?author=user2),  |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_empty_collaborators(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function with empty collaborators list.
        """
        collaborators = []
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            None,
            "org/repo",
            "false",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 0 | 0 | 0% |\n\n"
            "| Username | Company | All Time Contribution Count | New Contributor | "
            "Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_no_dates(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function without start and end dates.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "@company1",
            False,
            "url",
            100,
            "commit url",
            "sponsor_url_1",
        )
        person2 = contributor_stats.ContributorStats(
            "user2",
            "@company2",
            False,
            "url2",
            200,
            "commit url2",
            "sponsor_url_2",
        )
        collaborators = [
            person1,
            person2,
        ]
        ghe = ""

        write_to_markdown(
            collaborators,
            "filename",
            None,
            None,
            None,
            "org/repo",
            "false",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Repository: org/repo\n\n"
            "| Total Contributors | Total Contributions |\n"
            "| --- | --- |\n"
            "| 2  | 300  |\n\n"
            "| Username | Company | All Time Contribution Count | All Commits |\n"
            "| --- | --- | --- | --- |\n"
            "| @user1 | @company1 | 100 | commit url |\n"
            "| @user2 | @company2 | 200 | commit url2 |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)

    @patch(
        "markdown.os.environ.get", return_value=None
    )  # Mock GITHUB_STEP_SUMMARY to None
    @patch("builtins.open", new_callable=mock_open)
    def test_write_to_markdown_with_ghe(
        self, mock_file, mock_env_get
    ):  # pylint: disable=unused-argument
        """
        Test the write_to_markdown function with GitHub Enterprise URL.
        """
        person1 = contributor_stats.ContributorStats(
            "user1",
            "@company1",
            False,
            "url",
            100,
            "https://github.example.com/org1/repo1/commits?author=user1",
            "sponsor_url_1",
        )
        collaborators = [person1]
        ghe = "https://github.example.com"

        write_to_markdown(
            collaborators,
            "filename",
            "2023-01-01",
            "2023-01-02",
            "test-org",
            None,
            "false",
            True,
            ghe,
        )

        mock_file.assert_called_once_with("filename", "w", encoding="utf-8")
        # With the new implementation, content is written as a single string
        expected_content = (
            "# Contributors\n\n"
            "- Date range for contributor list:  2023-01-01 to 2023-01-02\n"
            "- Organization: test-org\n\n"
            "| Total Contributors | Total Contributions | % New Contributors |\n"
            "| --- | --- | --- |\n"
            "| 1 | 100 | 0.0% |\n\n"
            "| Username | Company | All Time Contribution Count | New Contributor | "
            "Commits between 2023-01-01 and 2023-01-02 |\n"
            "| --- | --- | --- | --- | --- |\n"
            "| @user1 | @company1 | 100 | False | "
            "[org1/repo1](https://github.example.com/org1/repo1/commits?author=user1),  |\n"
            "\n _this file was generated by the "
            "[Contributors GitHub Action]"
            "(https://github.com/github-community-projects/contributors)_\n"
        )
        mock_file().write.assert_called_once_with(expected_content)


if __name__ == "__main__":
    unittest.main()
